class MusicItemModel {
  final String songName;
  final String artistName;
  final Duration duration;
  final String? albumName;
  final String? coverUrl;
  bool isFavorite;

  MusicItemModel({
    this.albumName,
    this.coverUrl,
    required this.songName,
    required this.artistName,
    required this.duration,
    this.isFavorite = false,
  });
}

final List<MusicItemModel> musicList = [
  MusicItemModel(
    songName: 'Shape of You',
    artistName: 'Ed Sheeran',
    duration: Duration(minutes: 4, seconds: 24),
    albumName: 'Divide',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/4/45/Divide_cover.png',
  ),
  MusicItemModel(
    songName: 'Blinding Lights',
    artistName: 'The Weeknd',
    duration: Duration(minutes: 3, seconds: 20),
    albumName: 'After Hours',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/0/09/The_Weeknd_-_After_Hours.png',
  ),
  MusicItemModel(
    songName: 'Someone Like You',
    artistName: 'Adele',
    duration: Duration(minutes: 4, seconds: 45),
    albumName: '21',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1b/Adele_-_21.png',
  ),
  MusicItemModel(
    songName: 'Bad Guy',
    artistName: 'Billie Eilish',
    duration: Duration(minutes: 3, seconds: 14),
    albumName: 'When We All Fall Asleep, Where Do We Go?',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/7/7e/When_We_All_Fall_Asleep%2C_Where_Do_We_Go%3F.png',
  ),
  MusicItemModel(
    songName: 'Levitating',
    artistName: 'Dua Lipa',
    duration: Duration(minutes: 3, seconds: 23),
    albumName: 'Future Nostalgia',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/e/e1/Dua_Lipa_-_Future_Nostalgia_%28Official_Album_Cover%29.png',
  ),
  MusicItemModel(
    songName: 'Watermelon Sugar',
    artistName: 'Harry Styles',
    duration: Duration(minutes: 2, seconds: 53),
    albumName: 'Fine Line',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a0/Harry_Styles_-_Fine_Line.png',
  ),
  MusicItemModel(
    songName: 'Senorita',
    artistName: 'Shawn Mendes & Camila Cabello',
    duration: Duration(minutes: 3, seconds: 11),
    albumName: 'Romance',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/f/fd/Camila_Cabello_-_Romance.png',
  ),
  MusicItemModel(
    songName: 'Sunflower',
    artistName: 'Post Malone & Swae Lee',
    duration: Duration(minutes: 2, seconds: 38),
    albumName: 'Spider-Man: Into the Spider-Verse',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/4/4c/Post_Malone_and_Swae_Lee_-_Sunflower.png',
  ),
  MusicItemModel(
    songName: 'Circles',
    artistName: 'Post Malone',
    duration: Duration(minutes: 3, seconds: 35),
    albumName: 'Hollywood\'s Bleeding',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/1/18/Post_Malone_-_Hollywood%27s_Bleeding.png',
  ),
  MusicItemModel(
    songName: 'Drivers License',
    artistName: 'Olivia Rodrigo',
    duration: Duration(minutes: 4, seconds: 2),
    albumName: 'Sour',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/5/58/Olivia_Rodrigo_-_SOUR.png',
  ),
  MusicItemModel(
    songName: 'Good 4 U',
    artistName: 'Olivia Rodrigo',
    duration: Duration(minutes: 2, seconds: 58),
    albumName: 'Sour',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/5/58/Olivia_Rodrigo_-_SOUR.png',
  ),
  MusicItemModel(
    songName: 'Peaches',
    artistName: 'Justin Bieber',
    duration: Duration(minutes: 3, seconds: 18),
    albumName: 'Justice',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/8/88/Justin_Bieber_-_Justice.png',
  ),
  MusicItemModel(
    songName: 'Save Your Tears',
    artistName: 'The Weeknd',
    duration: Duration(minutes: 3, seconds: 35),
    albumName: 'After Hours',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/0/09/The_Weeknd_-_After_Hours.png',
  ),
  MusicItemModel(
    songName: 'Stay',
    artistName: 'The Kid LAROI & Justin Bieber',
    duration: Duration(minutes: 2, seconds: 21),
    albumName: 'Stay',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/9/9a/The_Kid_Laroi_and_Justin_Bieber_-_Stay.png',
  ),
  MusicItemModel(
    songName: 'Rockstar',
    artistName: 'DaBaby feat. Roddy Ricch',
    duration: Duration(minutes: 3, seconds: 2),
    albumName: 'Blame It on Baby',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/1/12/DaBaby_-_Blame_It_on_Baby.png',
  ),
  MusicItemModel(
    songName: 'Dakiti',
    artistName: 'Bad Bunny & Jhay Cortez',
    duration: Duration(minutes: 3, seconds: 25),
    albumName: 'El Último Tour Del Mundo',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/d/d9/Bad_Bunny_-_El_%C3%9Altimo_Tour_Del_Mundo.png',
  ),
  MusicItemModel(
    songName: 'Heat Waves',
    artistName: 'Glass Animals',
    duration: Duration(minutes: 3, seconds: 58),
    albumName: 'Dreamland',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/4/45/Dreamland_-_Glass_Animals.png',
  ),
  MusicItemModel(
    songName: 'Shivers',
    artistName: 'Ed Sheeran',
    duration: Duration(minutes: 3, seconds: 27),
    albumName: '= (Equals)',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/1/13/Ed_Sheeran_-_Equals.png',
  ),
  MusicItemModel(
    songName: 'Industry Baby',
    artistName: 'Lil Nas X & Jack Harlow',
    duration: Duration(minutes: 3, seconds: 32),
    albumName: 'Montero',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/2/20/Lil_Nas_X_-_Montero.png',
  ),
  MusicItemModel(
    songName: 'Easy On Me',
    artistName: 'Adele',
    duration: Duration(minutes: 3, seconds: 44),
    albumName: '30',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/9/9d/Adele_-_30.png',
  ),
  MusicItemModel(
    songName: 'Montero (Call Me By Your Name)',
    artistName: 'Lil Nas X',
    duration: Duration(minutes: 2, seconds: 17),
    albumName: 'Montero',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/2/20/Lil_Nas_X_-_Montero.png',
  ),
  MusicItemModel(
    songName: 'As It Was',
    artistName: 'Harry Styles',
    duration: Duration(minutes: 2, seconds: 47),
    albumName: 'Harry’s House',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/2/2e/Harry_Styles_-_Harry%27s_House.png',
  ),
  MusicItemModel(
    songName: 'Ghost',
    artistName: 'Justin Bieber',
    duration: Duration(minutes: 2, seconds: 33),
    albumName: 'Justice',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/8/88/Justin_Bieber_-_Justice.png',
  ),
  MusicItemModel(
    songName: 'Happier Than Ever',
    artistName: 'Billie Eilish',
    duration: Duration(minutes: 4, seconds: 58),
    albumName: 'Happier Than Ever',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/6/6c/Billie_Eilish_-_Happier_Than_Ever.png',
  ),
  MusicItemModel(
    songName: 'Positions',
    artistName: 'Ariana Grande',
    duration: Duration(minutes: 2, seconds: 52),
    albumName: 'Positions',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/7/70/Ariana_Grande_-_Positions.png',
  ),
  MusicItemModel(
    songName: '7 rings',
    artistName: 'Ariana Grande',
    duration: Duration(minutes: 2, seconds: 58),
    albumName: 'Thank U, Next',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/8/84/Ariana_Grande_-_Thank_U%2C_Next.png',
  ),
  MusicItemModel(
    songName: 'Memories',
    artistName: 'Maroon 5',
    duration: Duration(minutes: 3, seconds: 9),
    albumName: 'Jordi',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1e/Maroon_5_-_Jordi.png',
  ),
  MusicItemModel(
    songName: 'Don’t Start Now',
    artistName: 'Dua Lipa',
    duration: Duration(minutes: 3, seconds: 3),
    albumName: 'Future Nostalgia',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/e/e1/Dua_Lipa_-_Future_Nostalgia_%28Official_Album_Cover%29.png',
  ),
  MusicItemModel(
    songName: 'Tusa',
    artistName: 'KAROL G & Nicki Minaj',
    duration: Duration(minutes: 3, seconds: 20),
    albumName: 'Tusa',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/7/7a/Karol_G_and_Nicki_Minaj_-_Tusa.png',
  ),
  MusicItemModel(
    songName: 'Dance Monkey',
    artistName: 'Tones and I',
    duration: Duration(minutes: 3, seconds: 29),
    albumName: 'The Kids Are Coming',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/f/f8/Tones_and_I_-_The_Kids_Are_Coming.png',
  ),
];

